services:
  _defaults:
    public: false


  # Def resolver
  json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Resolver\DefinitionRefResolver

  ## Components
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.schema_type:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\SchemaTypeNormalizer
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.parameter_doc:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\TypeDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.schema_type'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.shape:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\ShapeNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.error:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\ErrorDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.parameter_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.external_schema_list:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\ExternalSchemaListDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.parameter_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.error'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.request_doc:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\RequestDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.response:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\ResponseDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.operation:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\App\Normalizer\Component\OperationDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.app.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.request_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.app.component.response'
