services:
  _defaults:
    public: true


  # Def resolver
  json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Resolver\DefinitionRefResolver


  # Normalizer
  json_rpc_http_server_open_api_doc_sdk.normalizer.doc:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\DocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.request_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.response'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.external_schema_list'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.operation'

  ## Components
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.schema_type:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\SchemaTypeNormalizer
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.parameter_doc:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\TypeDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.schema_type'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.shape:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\ShapeNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.error:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\ErrorDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.parameter_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.external_schema_list:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\ExternalSchemaListDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.parameter_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.error'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.request_doc:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\RequestDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.response:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\ResponseDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.shape'
  json_rpc_http_server_open_api_doc_sdk.normalizer.component.operation:
    class: Yoanm\JsonRpcHttpServerOpenAPIDoc\Normalizer\Component\OperationDocNormalizer
    arguments:
     - '@json_rpc_http_server_open_api_doc_sdk.resolver.definition_ref'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.request_doc'
     - '@json_rpc_http_server_open_api_doc_sdk.normalizer.component.response'
